### PR TITLE
fix #87

### LINKED ISSUE #87: Problem with writing code that line wraps
Reproduction: Hold the key 1. Every time it wraps around to a new line the input line is moved one line up.

### PR DESCRIPTION
**Pull request by pfitzseb**
I know you had some reason for removing that write, but everything still seems to work. And it fixes #87 :)

### CODE REVIEW

**Comment by KristofferC** [comment]
It does seem to work... Honestly, I have no idea why I removed it.

**Comment by pfitzseb** [comment]
> `# Pasted from LineEdit.jl but the writes to the Terminal have been removed.`

I'm sure there was *some* reason ;)

**Comment by KristofferC** [comment]
Ah, I think that I only used `refresh_multi_line` to set the cursor in the correct position. Which is why the writes are disabled. I'm not sure how I thought the newlines would ever be input for long lines though...

**Comment by pfitzseb** [comment]
Bump? :)

**Comment by KristofferC** [comment]
I was sure I merged this...

**Comment by KristofferC** [comment]
Oh yeah, the reason I didn't was that Travis hung.

**Comment by KristofferC** [comment]
Bu that seems to have been there earlier.

**Comment by KristofferC** [comment]
Made a new release.

**Pull request merged**
