### PR TITLE
Let's get rid of the flickering (again)

### PR DESCRIPTION
**Pull request by KristofferC**
Ok, so let's get this thing back!

The problem with some of the `buffer` calls is that some of the methods in Base does not define a `::IOBuffer` method.. Therefore, remove the use of `buffer(s)` for these functions.
I have tried all the overloaded keys now so things should work this time.

### CODE REVIEW

**Comment by KristofferC** [comment]
Does https://github.com/KristofferC/OhMyREPL.jl/pull/91/commits/f57cf6371666ce6ae662015a884016d9ce3ab48d makes sense to you @Keno?

**Comment by Keno** [comment]
Yes, but ideally we'd 1) have versions of these in base that take IOBuffers and 2) have tests for all the key bindings we're overwriting.

**Comment by KristofferC** [comment]
Regarding 2. I don't really understand how the testing is done. Is there somewhere I can read what all the letters in the `multiout` file means.

**Comment by Keno** [comment]
Well, there's two separate issues. First, we should just have a test that runs through all the key bindings and makes sure they don't error. The VT100-based test is useful for verifying the output, but as a first step we should just make a simple test to invoke all the key bindings. As for the multiout file, the letters are formatting. In this particular instance, they're just assigned sequentially, which was good enough for me to test all the output is there and that the highlighting is applied (without caring about the specific colors etc). There is a way to specify an assignment though rather than do it sequentially. In any case, I'd be happy to take a look at writing some tests next week, or at least get things all set up to write the tests.

**Comment by KristofferC** [comment]
Ok, cool. I tested stuff manually again and things seems to work well. I'll merge and tag this since this is such a nice improvement. Can always add the tests later. Thanks again.

**Pull request merged**
