### PR TITLE
add Fzf search

### LINKED ISSUE #204: Add fzf fuzzy search to REPL
Love using OhMyREPL, but I miss the `Ctrl-r` fuzzy search to find a command that is 10 lines away or yesterday, the original fzf package can be found [here](https://github.com/junegunn/fzf).

I already made [fzf_jll](https://github.com/JuliaBinaryWrappers/fzf_jll.jl) and a wrapper [module](https://github.com/Moelf/Fzf.jl) for it that can interactively search `repl_history.jl` (`inter_fzf(Fzf.read_repl_hist())`).

Wondering if this is a welcome enhancement, and if so where should I add this (key-binding / result substitution)

Thx!

### PR DESCRIPTION
**Pull request by Moelf**
fix #204

### CODE REVIEW

**Comment by KristofferC** [comment]
Woow, this is so cool.

**Comment by KristofferC** [comment]
It seems to work slightly weird on Windows.

Entering some stuff:
Screenshot-20200901123553-250x217

Selecting `3+3` and pressing enter
Screenshot-20200901123620-160x113

Dark REPL:

Screenshot-20200901123626-174x190

Type something:
Screenshot-20200901123728-209x164

**Comment by KristofferC** [comment]
I don't know what happened here. I tried to update the branch and it closed.

Continue in https://github.com/KristofferC/OhMyREPL.jl/pull/210.

**Comment by musm** [comment]
Testing in the Windows Terminal I'm not sure I see any problems  with Fzf search:

**Comment by KristofferC** [comment]
Well, one thing is that it cleared your screen. But you didn't have the black screen after you selected something.

**Comment by musm** [comment]
Right the only thing is that it "clears the screen" after enter something, but other than that it's not bad.

**Pull request closed without merging**
