### PR TITLE
add @code_src

### PR DESCRIPTION
**Pull request by Moelf**
image

### CODE REVIEW

**Comment by KristofferC** [comment]
Seems OK to me but I wonder a bit how useful this is in practice. By using `@edit` you open your editor which also has highlighting.

**Comment by Moelf** [comment]
I think:
https://github.com/JuliaLang/julia/issues/2625#issuecomment-498840808

**Comment by Moelf** [comment]
@KristofferC pretty sure docs build fail is unrelated

**Comment by Moelf** [comment]
bump

**Comment by Moelf** [comment]
gentle bump

**Comment by KristofferC** [comment]
Sorry for the slow response here. I've been hardcore neglecting this package for quite a while.

Looking at this with fresh eyes I don't think it really fits very well in here. And the way this is implemented by adding a whole new macro as a side effect of loading another package is quite unusual. Typically, you want to add a method extension but that is kind of hard to macros. And I also don't really want to add a dependency on Requires.

**Pull request closed without merging**
