### PR TITLE
Fix a number of instances of flickering

### PR DESCRIPTION
**Pull request by Keno**
The most common cause of flickering is that there is a repaint
between sequences that are meant to be interpreted together.
This can be avoided by buffering sequences first and then
writing them out all at once. Do this, and add testing infrastructure
to verify that it stays this way.

### CODE REVIEW

**Comment by KristofferC** [comment]
Thanks a lot, this is wonderful! This has been a long standing problem and from what I have heard a reason people have stopped using this package. The testing interface is also a sorely needed addition.

Seems to be some problem with the VT100 requirement such that Pkg is not happy.

**Comment by Keno** [comment]
I had to tag a new version of VT100 to fix some misunderstand I had of the spec. If you restart travis it should go through fine.

**Comment by KristofferC** [comment]
I think TerminalUI needs to be in REQUIRE as well?

**Comment by Keno** [comment]
Ah sorry about that, I'd only used TerminalUI for debugging the intermediate state, since it has interactive widgets to do that. It's not required for the actual test.

**Comment by Keno** [comment]
Hmm, works in isolation, but not as part of the test suite. Looks like it fails to highlight the brackets in `a = b()`. Does the test suite mess with some sort of global setting?

**Comment by KristofferC** [comment]
Possible workaround while figuring that out, put your test file as the first to be included? :D

**Comment by Keno** [comment]
Yeah, but I figured it out. It's the colorsheme! in test_highlighter. For now I'll put the test first and let you figure out the right solution ;).

**Comment by KristofferC** [comment]
Thanks again, will tag a new release with this.

**Comment by KristofferC** [comment]
I reverted this PR because there was some stuff that didn't work perfectly. Right now, I am in a position where working too much on this will get my ass kicked so I'll test it a bit more carefully and try fixup the small stuff and tag a new version with this in a couple of days.

**Comment by sbromberger** [comment]
Just a datapoint here:
```
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.5.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```
No flickering at all!! :) 🍾

**Pull request merged**
