### PR TITLE
Hide the cursor when rewriting

### PR DESCRIPTION
**Pull request by rsrock**
This reduces the flicker when using a block cursor.

### CODE REVIEW

**Comment by KristofferC** [comment]
Cool! This helps a lot. Does this work on Windows too (as in, it Windows CMD doesn't freak out from this ANSI code)?

**Comment by rsrock** [comment]
Good question, I hadn't considered it.  I can test on a Windows computer in the lab, but I have deadlines that will block this for at least a couple of weeks.

**Comment by KristofferC** [comment]
Ok I'll try it out myself then.

**Comment by KristofferC** [comment]
Commit added in https://github.com/KristofferC/OhMyREPL.jl/pull/83

**Pull request closed without merging**
