### PR TITLE
add fzf --multiple/-m

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by KristofferC** [comment]
This doesn't work for me. I go into the fzf list but pressing tab doesn't seem to do anything.

**Comment by tecosaur** [comment]
Curious. What about trying `fzf -m` in a terminal?

**Comment by KristofferC** [comment]
Yes, that seems to work.

**Comment by tecosaur** [comment]
Well, all I think I can add here is that `-m` work in-terminal and in-Julia-repl for me (v1.6 and v1.7).

**Comment by KristofferC** [comment]
Ok, it does work for me, I guess I messed up somehow.

**Pull request merged**
