### PR TITLE
change precompile strategy to FakePTYs

### PR DESCRIPTION
**Pull request by KristofferC**
@johnnychen94, can you try this?

### CODE REVIEW

**Comment by KristofferC** [comment]
Seems to error on Windows for some reason...

**Comment by johnnychen94** [comment]
It works on 67e3c06

**Comment by KristofferC** [comment]
Yes because I disabled it on Windows there heh.

**Comment by KristofferC** [comment]
I'll merge this to get the issue in https://github.com/KristofferC/OhMyREPL.jl/pull/296#discussion_r1136618854 fixed. Then I can work on figuring out why it doesn't work on Windows..

**Pull request merged**
