### PR TITLE
Revert "Merge in OhMyLog (#130)"

### LINKED ISSUE #146: OhMyREPL logging can crash when showing normal logs
Reported in slack that the log handling in OhMyREPL crashes when some logging happens:

```
Exception handling log message: MethodError(OhMyREPL.showvalue, (IOContext(IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)), (CUDAnative.MethodSubstitutionWarning(exp(x::T) where T<:Union{Float32, Float64} in Base.Math at special/exp.jl:75, exp(x::Float32) in CUDAnative at C:\Users\jules\.julia\packages\CUDAnative\Mdd3w\src\device\libdevice.jl:90), Base.StackTraces.StackFrame[exp at exp.jl:75, mapreducedim_kernel_parallel at mapreduce.jl:29]), :exception), 0x0000000000006322)
  module=CUDAnative  file=C:\Users\jules\.julia\packages\CUDAnative\Mdd3w\src\compiler\irgen.jl  line=68
  Second exception: MethodError(OhMyREPL.showvalue, (IOContext(IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)), (MethodError(OhMyREPL.showvalue, (IOContext(IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)), (CUDAnative.MethodSubstitutionWarning(exp(x::T) where T<:Union{Float32, Float64} in Base.Math at special/exp.jl:75, exp(x::Float32) in CUDAnative at C:\Users\jules\.julia\packages\CUDAnative\Mdd3w\src\device\libdevice.jl:90), Base.StackTraces.StackFrame[exp at exp.jl:75, mapreducedim_kernel_parallel at mapreduce.jl:29]), :exception), 0x0000000000006322), Union{Ptr{Nothing}, InterpreterIP}[Ptr{Nothing} 
```

Not loading OhMyREPL made the correct warnings appear.

cc @oxinabox

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #146

### CODE REVIEW

**Comment by KristofferC** [comment]
Based on https://github.com/KristofferC/OhMyREPL.jl/issues/146#issuecomment-459032964.

**Comment by oxinabox** [comment]
Did you use the standard git revert?
If so this is nice,
I guess it does joing boild dow nto inverting the diffs then applying patch

**Comment by KristofferC** [comment]
Yes used a `git revert`.

**Comment by oxinabox** [comment]
what a wonderful world

**Pull request merged**
