### PR TITLE
Update prompt.jl

### PR DESCRIPTION
**Pull request by eloualiche**
Allow for integer to call Base.text_colors to change the colors in the prompt.

I think this fixes some of the issues mentioned here: https://github.com/KristofferC/OhMyREPL.jl/issues/258

### CODE REVIEW

**Review by Moelf — APPROVED** [review]

**Comment by KristofferC** [comment]
Needs some kind of documentation for people to be able to use this.

**Comment by eloualiche** [comment]
I added an example in the documentation; also I added the integer choice for output and fixed the type in the doc.

**Comment by eloualiche** [comment]
Also I did not see a documentation for the color choices anywhere so I took a screenshot for each integer. 
I wonder where this could fit or whether this could be useful?

Screen Shot 2022-02-04 at 16 57 52

**Comment by Moelf** [comment]
doesn't the "number -> actual color on your screen" depend on your terminal's palette?

**Comment by eloualiche** [comment]
Good question. My guess is that it depends to some extent to my palette. 
But tbh, I could not find any mention of using Base.text_colors anywhere. I just think it would nice to have it somewhere. 

Here is the blurb:
```julia
dint = filter( p -> first(p) isa Int, Base.text_colors)
for (key, value) in dint
    print(value); print("▐"*string(key)); 
end
```

Btw, this is a little bit of a tangent and has nothing to do with the PR at this point.

**Comment by Moelf** [comment]
image

my suggestion is to not show this screenshot, it's not relevant to the API, basically we just need to tell users this is 256 color pallet in some terminal etc. (some terminals have true color support)

**Comment by KristofferC** [comment]
Thanks, and sorry for the very slow feedback here.

**Pull request merged**
