### PR TITLE
Document Tomorrow Night Bright schemes

### PR DESCRIPTION
**Pull request by mkborregaard**
Sorry, forgot to document the color scheme. I think this is the only important place.

### CODE REVIEW

**Comment by KristofferC** [comment]
Perfect, thanks.

**Comment by KristofferC** [comment]
I should work on getting some light background colorschemes in. The ones in the latest Sublime build were pretty good.

**Comment by KristofferC** [comment]
It doesnt look like you used the values from https://github.com/chriskempson/tomorrow-theme#tomorrow-night-bright or?

**Comment by mkborregaard** [comment]
I did use those values, and subjected the hex codes to `asrgb(x) = round.(Int,getfield.(parse(Colorant, x),1:3).*255)`. Are you seeing any inconsistencies?

**Pull request merged**
