### PR TITLE
Show any unexpected stderr output during __init__

### PR DESCRIPTION
**Pull request by tkelman**
Should be somewhat less error-prone, to only hide exactly the expected warnings instead of every possible problem that might be going to stderr at load time.

### CODE REVIEW

**Comment by KristofferC** [comment]
I've had a lot of problems when redirecting the io, https://github.com/KristofferC/OhMyREPL.jl/issues/40, https://github.com/KristofferC/OhMyREPL.jl/issues/35, https://github.com/KristofferC/OhMyREPL.jl/issues/14 so I'm a bit reluctant to touch that. Writing to a temp file seems to at least consistently work.

**Comment by tkelman** [comment]
This isn't touching it much, only enough to check what ends up there and show it if unexpected.

**Comment by KristofferC** [comment]
Oh sorry, I misunderstood the change.

**Comment by KristofferC** [comment]
Thanks :+1:

**Pull request merged**
